### ISSUE TITLE
Output is scaled incorrectly on macOS

### ISSUE THREAD

**Issue by shepmaster** [Osspial/derin-rs#7]
After making the diff in #6 , I see this output:

<img width="512" alt="screen shot 2018-03-07 at 8 18 27 pm" src="https://user-images.githubusercontent.com/174509/37127654-c2038104-2244-11e8-96ed-7ec24d33744d.png">

Perhaps due to a HiDPI screen?

**Comment by Osspial** [comment]
This should be fixed by cee6bd291be3212b649e986118e5f4b7ad79fcae. Proper HiDPI support still needs to be implemented to get text looking crisp, but it should be rendering properly now.

**Comment by Osspial** [comment]
Closed in favor of #8.
